name: ahk2exe

on: [push]

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Ahk2Exe
      uses: tamo/action-Ahk2Exe@main
      with:
        base: AutoHotkey32.exe,AutoHotkey64.exe
        src: BlackSpotPerMonitor.ahk

    - run: |
        Get-ChildItem BlackSpotPerMonitor32.exe
        Get-ChildItem BlackSpotPerMonitor64.exe
        Move-Item BlackSpotPerMonitor32.exe BlackSpotPerMonitor.exe

    - name: Sign
      env:
        CERTPASS: ${{ secrets.CERTPASS }}
        SIGNCERT: ${{ secrets.SIGNCERT }}
      run: |
        $key = [System.Convert]::FromBase64String($env:SIGNCERT)
        $cert = [System.Security.Cryptography.X509Certificates.X509Certificate2]::New($key, $env:CERTPASS)
        Set-AuthenticodeSignature BlackSpotPerMonitor.exe -Certificate $cert
        Set-AuthenticodeSignature BlackSpotPerMonitor64.exe -Certificate $cert

    - run: Remove-Item uia/makecert.ps1,uia/sign.ps1

    - name: Archive
      run: Compress-Archive -Path uia -DestinationPath uia.zip

    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        path: |
          BlackSpotPerMonitor.exe
          BlackSpotPerMonitor64.exe
          uia.zip

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          BlackSpotPerMonitor.exe
          BlackSpotPerMonitor64.exe
          uia.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
